// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP6mqbNhCv6QMZyF1yAbEdMmO8WdKDsLs',
    appId: '1:221967167062:web:ef60e9a1a278891b2c55f7',
    messagingSenderId: '221967167062',
    projectId: 'examecom-cc34d',
    authDomain: 'examecom-cc34d.firebaseapp.com',
    storageBucket: 'examecom-cc34d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPQFZSUzPgVCrgOE53xMwDO4wn86UDw1U',
    appId: '1:221967167062:android:a19acebd5c0b66d12c55f7',
    messagingSenderId: '221967167062',
    projectId: 'examecom-cc34d',
    storageBucket: 'examecom-cc34d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsuNB0vw65-IsX7lxHzRvqTctzzCPsbC0',
    appId: '1:221967167062:ios:34e7187d9a2c01eb2c55f7',
    messagingSenderId: '221967167062',
    projectId: 'examecom-cc34d',
    storageBucket: 'examecom-cc34d.firebasestorage.app',
    iosBundleId: 'com.example.ecomEfm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsuNB0vw65-IsX7lxHzRvqTctzzCPsbC0',
    appId: '1:221967167062:ios:34e7187d9a2c01eb2c55f7',
    messagingSenderId: '221967167062',
    projectId: 'examecom-cc34d',
    storageBucket: 'examecom-cc34d.firebasestorage.app',
    iosBundleId: 'com.example.ecomEfm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP6mqbNhCv6QMZyF1yAbEdMmO8WdKDsLs',
    appId: '1:221967167062:web:b372dd8bbc4ac04d2c55f7',
    messagingSenderId: '221967167062',
    projectId: 'examecom-cc34d',
    authDomain: 'examecom-cc34d.firebaseapp.com',
    storageBucket: 'examecom-cc34d.firebasestorage.app',
  );

}